name: javelin
description: Data Driven Games
version: 0.1.0
authors:
- John McCutchan <john@johnmccutchan.com>
- Daniel Rodríguez <seth.illgard@gmail.com>
homepage: https://github.com/johnmccutchan/javelin
dependencies:
  unittest: any
  marker_prof:
    git: https://github.com/johnmccutchan/markerprof.git
  vector_math:
    git: https://github.com/johnmccutchan/DartVectorMath.git
  spectre:
    git: https://github.com/johnmccutchan/spectre.git
  property_map:
    git: https://github.com/sethillgard/property_map.git
